---
- name: Deploy Unifi Controller
  hosts: unifi
  become: True
  tasks:
    - import_role:
        name: common
    - import_role:
        name: docker
    - import_role:
        name: unifi
    - import_role:
        name: telegraf
