---
- name: "[Ubiquiti] :: Deploy Ubiquiti management services Unifi-Admin and UNMS with Monitoring Services (Telegraf, Unifi-Prometheus-Exporter).  Includes OpenLDAP-Client, CephFS/NFS"
  hosts: unifi
  become: True
  tasks:
    - include_role:
        name: common
    - include_role:
        name: openldap
      when:  openldap_server_ip is defined and openldap_server_ip != None
    - include_role:
        name: ceph-fs
      when:
        - shared_storage
        - storage_backend == "cephfs"
    - include_role:
        name: nfs
      when:
        - shared_storage
        - storage_backend == "nfs"
    - include_role:
        name: unifi
      tags:
        - unifi
        - unifi_admin
        - unms
        - exporter
    - include_role:
        name: docker
    - include_role:
        name: unifi
        tasks_from: unifi_admin_ssl
        apply:
          tags:
            - unifi
            - unifi_admin
            - unifi_admin_ssl
      tags:
        - unifi_admin_ssl
    - include_role:
        name: telegraf
      when: "'telegraf' in group_names"
