---
- name: Unifi Admin
  include_tasks: unifi_admin.yml
  tags: unifi_admin

- name: UNMS
  include_tasks: unms.yml
  tags: unms

- name: Unifi Exporter
  include_tasks: unifi_exporter.yml
  tags: exporter
