---
- name: Unifi Admin
  import_tasks:
    file: unifi_admin.yml
  when: "'unifi' in group_names"

- name: UNMS
  import_tasks:
    file: unms.yml
  when: "'unms' in group_names"

- name: Unifi Exporter
  import_tasks:
    file: unifi_exporter.yml
  when: "'unifi' in group_names"

- name: Build Unifi Admin SSL Cert
  import_tasks:
    file: unifi_admin_ssl.yml
  when: "'unifi' in group_names"
