---

- name: Ensure Unifi Data Directory Exists
  file:
    state: directory
    path: '{{ unifi_data_directory }}'
    owner: root
    group: root

- name: Install SSL Key
  copy:
    content: "{{ vault_prettybaked_com_ssl_private_key }}"
    dest: "{{ ssl_private_key }}"
    owner: root
    group: root
    mode: 0640

- name: Install SSL Certificate Chain
  copy:
    content: "{{ vault_prettybaked_com_ssl_certificate }}"
    dest: "{{ ssl_certificate }}"
    owner: root
    group: root
    mode: 0640

- name: Create SSL Import Script
  template:
    src: unifi_ssl_import.sh.j2
    dest: '{{ unifi_config_directory }}/unifi_ssl_import.sh'
    mode: 0775
    owner: root
    group: root

- name: Build SSL Keystore for Unifi Admin
  shell: '{{ unifi_config_directory }}/unifi_ssl_import.sh >> /var/log/docker_unifi_ssl_upgrade.log'
  args:
    executable: /bin/bash
  notify: restart_docker_unifi
