---
- name: Install UNMS
  shell: "curl -fsSL https://unms.com/install > /tmp/unms_inst.sh && sudo bash /tmp/unms_inst.sh --data-dir={{ unms_config_directory }} --unattended --ssl-cert={{ ssl_certificate }} --ssl-cert-key={{ ssl_private_key }} --branch={{ unms_branch }}"
  args:
    executable: /bin/bash
    creates: /tmp/unms_inst.sh
  environment:
    UNMS_HOME_DIR: '{{ unms_config_directory }}'

