---

- name: Create local UNMS group
  group:
    name: unms
    gid: 1000
    state: present

- name: Create local UNMS user
  user:
    name: unms
    uid: 1000
    group: unms
    create_home: yes
    home: /var/lib/unms

- name: Ensure UNMS Config Directories Exist
  file:
    state: directory
    path: '{{ unms_config_directory }}/data/cert'
    owner:  unms

- name: Install SSL Key
  copy:
    content: "{{ ssl_privkey }}"
    dest: "{{ unms_ssl_keypath }}"
    owner: unms
    mode: 0600
  when: unms_enable_ssl

- name: Install SSL Certificate Chain
  copy:
    content: "{{ ssl_certchain }}"
    dest: "{{ unms_ssl_certpath }}"
    owner: unms
    mode: 0600
  when: unms_enable_ssl

- name: Check for UNMS container services
  command: "docker ps -q -f name=unms"
  args:
    executable: /bin/bash
  register: unms_containers
  changed_when: False

- name: Install UNMS
  shell: "curl -fsSL https://unms.com/v1/install > /tmp/unms_inst.sh && bash /tmp/unms_inst.sh --data-dir={{ unms_config_directory }} --unattended --update"
  args:
    executable: /bin/bash
  when: unms_containers.stdout_lines | length < 7
  environment:
    UNMS_HOME_DIR: '{{ unms_config_directory }}'
