---

- name: Create local UNMS group
  group:
    name: unms
    state: present
  register: unms_group_create

- debug:
    var: unms_group_create.gid
  tags:
    - never
    - debug

- name: Create local UNMS user
  user:
    name: unms
    uid: "{% if unms_user_id is defined %}{{ unms_user_id }}{% else %}{{ omit }}{% endif %}"
    group: "{{ unms_group_create.gid }}"
    create_home: yes
    home: /var/lib/unms
  register: unms_user_create

- debug:
    var: "unms_user_create.uid"
  tags:
    - never
    - debug

- name: Ensure UNMS Config Directories Exist
  file:
    state: directory
    path: '{{ item }}'
    owner: "{{ unms_user_create.uid }}"
    group: "{{ unms_group_create.gid }}"
  loop:
    - "{{ unms_config_directory }}"
    - "{{ unms_data_directory }}"
    - "{{ unms_app_directory }}"
    - "{{ unms_pgconf_directory }}"
    - "{{ unms_log_directory }}"
    - "{{ unms_redis_directory }}"
    - "{{ unms_postgres_directory }}"
    - "{{ unms_rabbitmq_directory }}"
    - "{{ unms_ucrm_directory }}"
    - "{{ unms_firmware_directory }}"
    - "{{ unms_cert_directory }}"
    - "{{ unms_siridb_directory }}"

- name: Create UNMS postgresql user script
  template:
    src: create-users.sh.j2
    dest: "{{ unms_pgconf_directory }}/create-users.sh"
    owner: "{{ unms_user_create.uid }}"
    group: "{{ unms_group_create.gid }}"
    mode: 0775

- name: Install SSL Key
  copy:
    content: "{{ ssl_privkey }}"
    dest: "{{ unms_cert_directory }}/localhost.key"
    owner: "{{ unms_user_create.uid }}"
    group: "{{ unms_group_create.gid }}"
    mode: 0600
  when: unms_enable_ssl

- name: Install SSL Certificate Chain
  copy:
    content: "{{ ssl_certchain }}"
    dest: "{{ unms_cert_directory }}/localhost.crt"
    owner: "{{ unms_user_create.uid }}"
    group: "{{ unms_group_create.gid }}"
    mode: 0600
  when: unms_enable_ssl

- name: Relink UNMS SSL Cert
  file:
    state: link
    src: "localhost.crt"
    dest: "{{ unms_cert_directory }}/live.crt"
    owner: "{{ unms_user_create.uid }}"
    group: "{{ unms_group_create.gid }}"

- name: Relink UNMS SSL Cert
  file:
    state: link
    src: "localhost.key"
    dest: "{{ unms_cert_directory }}/live.key"
    owner: "{{ unms_user_create.uid }}"
    group: "{{ unms_group_create.gid }}"


- name: Import SNMP Collection Tasks
  import_tasks:
    file: snmp_collection.yml


#- name: Check for UNMS container services
#  shell: "docker ps -q -f name=unms"
#  args:
#    executable: /bin/bash
#  register: unms_containers
#  changed_when: False
#
#- name: Install UNMS
#  get_url:
#    url: https://unms.com/v1/install
#    dest: /tmp/unms_inst.sh
#    owner: "{{ unms_user_create.uid }}"
#    group: "{{ unms_group_create.gid }}"
#    group: unms
#    mode: 0775
#  when: unms_containers.stdout_lines | length < 7
#
#- name: Install UNMS
#  shell:
#    cmd: /tmp/unms_inst.sh --data-dir {{ unms_data_directory }} --ssl-cert-dir {{ unms_cert_directory }} --ssl-cert {{ unms_ssl_cert }} --ssl-cert-key {{ unms_ssl_key }} --unattended --upgrade
#    executable: /bin/bash
#    chdir: /tmp
#  when: unms_containers.stdout_lines | length < 7
