---

- name: Create local UNMS group
  group:
    name: unms
    state: present

- name: Create local UNMS user
  user:
    name: unms
    uid: "{{ unms_user_id }}"
    group: unms
    create_home: yes
    home: /var/lib/unms

- name: Ensure UNMS Config Directories Exist
  file:
    state: directory
    path: '{{ item }}'
    owner:  unms
  loop:
    - "{{ unms_config_directory }}"
    - "{{ unms_data_directory }}"
    - "{{ unms_app_directory }}"
    - "{{ unms_pgconf_directory }}"
    - "{{ unms_log_directory }}"
    - "{{ unms_redis_directory }}"
    - "{{ unms_postgres_directory }}"
    - "{{ unms_rabbitmq_directory }}"
    - "{{ unms_ucrm_directory }}"
    - "{{ unms_firmware_directory }}"
    - "{{ unms_cert_directory }}"

- name: Create UNMS postgresql user script
  template:
    src: create-users.sh.j2
    dest: "{{ unms_pgconf_directory }}/create-users.sh"
    owner: unms
    mode: 0775

- name: Install SSL Key
  copy:
    content: "{{ ssl_privkey }}"
    dest: "{{ unms_cert_directory }}/localhost.key"
    owner: unms
    mode: 0600
  when: unms_enable_ssl

- name: Install SSL Certificate Chain
  copy:
    content: "{{ ssl_certchain }}"
    dest: "{{ unms_cert_directory }}/localhost.crt"
    owner: unms
    mode: 0600
  when: unms_enable_ssl

- name: Relink UNMS SSL Cert
  file:
    state: link
    src: "localhost.crt"
    dest: "{{ unms_cert_directory }}/live.crt"
    owner: unms

- name: Relink UNMS SSL Cert
  file:
    state: link
    src: "localhost.key"
    dest: "{{ unms_cert_directory }}/live.key"
    owner: unms

#- name: Check for UNMS container services
#  shell: "docker ps -q -f name=unms"
#  args:
#    executable: /bin/bash
#  register: unms_containers
#  changed_when: False
#
#- name: Install UNMS
#  get_url:
#    url: https://unms.com/v1/install
#    dest: /tmp/unms_inst.sh
#    owner: unms
#    group: unms
#    mode: 0775
#  when: unms_containers.stdout_lines | length < 7
#
#- name: Install UNMS
#  shell:
#    cmd: /tmp/unms_inst.sh --data-dir {{ unms_data_directory }} --ssl-cert-dir {{ unms_cert_directory }} --ssl-cert {{ unms_ssl_cert }} --ssl-cert-key {{ unms_ssl_key }} --unattended --upgrade
#    executable: /bin/bash
#    chdir: /tmp
#  when: unms_containers.stdout_lines | length < 7
