- name: restart_docker_unifi
  service:
    name: docker-unifi
    state: restarted
- name: restart unifi_exporter
  systemd:
    name: docker-unifi_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes
