- name: restart docker_unifi
  systemd:
    name: docker-unifi
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart unifi_exporter
  systemd:
    name: docker-unifi_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes
